name = "BDSUC"
uuid = "021037c4-aabf-4c8f-993e-67c4649a0194"
authors = ["MathisAzema <az_mathis@orange.fr>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
Gurobi = "1.7.4"
JuMP = "1.26.0"
NCDatasets = "0.14.8"
Plots = "1.40.13"
Statistics = "1.11.1"
XLSX = "0.10.4"